### ISSUE TITLE
Feature: Ability to mount web directory

### ISSUE THREAD

**Issue by Aetherinox** [jgomez177/plex-for-channels#7]
I got the webserver working. But I was wondering if you could modify the Dockerfile to allow the `/app/plex_data` to be mounted as a normal volume?

I have another container that works similarly to this image but for Pluto TV.

When I went to mount the folder for this container, it does nothing. Unless I'm doing something wrong.

```yml
    jellyfin-scraper-plex:
        container_name: ${JELLYFIN_SCRAPER_PLEX_CONTAINER_NAME:-jellyfin-scraper-plex}
        image: ${JELLYFIN_SCRAPER_PLEX_IMAGE:-ghcr.io/jgomez177/plex-for-channels}:${JELLYFIN_SCRAPER_PLEX_TAG:-latest}
        restart: unless-stopped
        volumes:
            - /home/docker/www/cdn.domain.com:/app/plex_data
        environment:
            - TZ=Etc/UTC
            - PLEX_CODE=local
            - PLEX_PORT=7777
```

I saw your note under the section `Optional Custom Gracenote ID Matching`, but for some reason, when I attempt to mount, nothing at all happens. no permission errors, and when I `sh` into the container, I can see the xml and m3u files generated in that folder.
